---
# tasks file for wordpress
- name: copy image wordpress  to remotely server 
  copy:
    src: services/wordpress
    dest: /tmp/services

- name: Build ft_nginx
  ansible.builtin.command:
    cmd: docker build -t ft_wordpress  /tmp/services/wordpress/